### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by ak0815** [WenchaoD/FSPagerView#14]
Hi,

if I set:
pagerView.itemSize = CGSize(width: 100, height: 100)

I get this error:

`2017-02-24 19:35:44.423 ccs[62442:3672487] *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UICollectionViewData.m:433
2017-02-24 19:35:44.433 ccs[62442:3672487] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x600000c301e0> {length = 2, path = 1 - 0}'`

if I set it to:
pagerView.itemSize = CGSize(width: 120, height: 120)
it works

Why?

Thanks

**Comment by WenchaoD** [comment]
Fixed. Thanks for posting this.

**Comment by networkharry04** [comment]
Hi, 

I am facing crash issue as mentioned below when i try to run - Here are my findings  - 

I have set - self.pagerView.itemSize = CGSize(width: self.pagerView.frame.width-700, height: self.pagerView.frame.height-250)

My images array contain 15 items , that i need to load using this library. But when I debug the issue and print method names and index path where it is crashing  - it run till index path [0,8] and then crash , please help me to figure out the issue. 

layoutAttributesForElements ->> [0, 0]
layoutAttributesForItem - >> [0, 0]
layoutAttributesForElements ->> [0, 1]
layoutAttributesForItem - >> [0, 1]
layoutAttributesForElements ->> [0, 2]
layoutAttributesForItem - >> [0, 2]
layoutAttributesForElements ->> [0, 3]
layoutAttributesForItem - >> [0, 3]
layoutAttributesForElements ->> [0, 4]
layoutAttributesForItem - >> [0, 4]
layoutAttributesForElements ->> [0, 5]
layoutAttributesForItem - >> [0, 5]
layoutAttributesForElements ->> [0, 6]
layoutAttributesForItem - >> [0, 6]
layoutAttributesForElements ->> [0, 7]
layoutAttributesForItem - >> [0, 7]
layoutAttributesForElements ->> [0, 8]
layoutAttributesForItem - >> [0, 8]

 
*** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.94.9/UICollectionViewData.m:447
2019-01-25 00:23:08.137028+0530 GWG[6133:2386201] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x282b72ea0> {length = 2, path = 0 - 0}'
