### ISSUE TITLE
Why do this in adjustCollectionViewBounds here?

### ISSUE THREAD

**Issue by broccolii** [WenchaoD/FSPagerView#4]
Why origin is set to contentOffset
Bounds of the origin of the default is (0, 0 )

**Comment by WenchaoD** [comment]
Hi @broccolii 
1. About the function ***adjustCollectionViewBounds***: The purpose of the function is to ensure that every time the layout in invalidated (For example the device orientation has changed, or the item size has changed), the original item before the invalidation in the middle in the pagerView is still in the middle.
2. Why origin is set to contentOffset: The ***contentOffset*** is the origin of the ***bounds*** of the UIScrollView. You can see the explanation in [the documentation](https://developer.apple.com/reference/uikit/uiscrollview/1619404-contentoffset). The reason I change the ***bounds*** rather than the ***contentOffset*** is that I don't want the delegate method ***scrollViewDidScroll*** get fired.

Thanks.

**Comment by broccolii** [comment]
Thank you very much for taking the time to answer my puzzles~~
