### ISSUE TITLE
Reason for weak property

### ISSUE THREAD

**Issue by SketchK** [WenchaoD/FSPagerView#87]
FSPagerView is amazing and I try my best to read the source code. 
I find some thing interesting and i can't explain it by myself, so i come here to ask help.
**Why you declare [these properties](https://github.com/WenchaoD/FSPagerView/blob/master/Sources/FSPagerView.swift#L204-L206)  as weak ?**
**What will happen if i delete weak syntax ?** 
Could you explain the reason for me?  
Thank you : ]

**Comment by WenchaoD** [comment]
Why the `layout` declared as weak?  Because A view has already retained all it subviews, including the collection view, and the collection view already retained it's layout. 

But it's intuitive to declare them as weak, which means `I am not responsible for memory-management of these properties. If they happen to leak, it's not my business`.

But it's ok if you delete the weak syntax and no compile/runtime error will occur.
